name: panda_tv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  tmdb_api: ^2.2.3
  webview_flutter: ^4.7.0
   # Or your version
  webview_flutter_web:
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
